name: DataMiner CICD NuGet Solution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events.
  push:
    branches: 
      - '*'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+-**"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

# Note: Tagging will push the nupackage to nuget.org using the provided NUGETAPIKEY. You can tag both a prerelease version (a.b.c-xxxx) or a stable release (a.b.c).
  CICD:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/NuGet Solution Master Workflow.yml@main
    with:
      referenceName: ${{ github.ref_name }}
      runNumber: ${{ github.run_number }}
      referenceType: ${{ github.ref_type }}
      repository: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      sonarCloudProjectName: "SkylineCommunications_Skyline.DataMiner.Utils.DOM"
    secrets:
      sonarCloudToken: ${{ secrets.SONAR_TOKEN }}
      pfx: ${{ secrets.PFX }}
      pfxPassword: ${{ secrets.PFXPASSWORD }}
      nugetApiKey: ${{ secrets.NUGETAPIKEY }}
